spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}?useTimezone=true&serverTimezone=America/Sao_Paulo&CreateDatabaseIfNotExists=true
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    dialect: org.hibernate.dialect.MySQL5Dialect