version: '3.8'
services:
  db:
    container_name: poc_insider
    image:  mysql/mysql-server
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - config/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  db_data: { }